name: Build Keyring-Utilities
permissions:
  id-token: write
  issues: write
  pull-requests: write
  contents: write
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      PERFORM_RELEASE:
        description: '[Release] perform release'
        required: false
        default: 'false'

jobs:
  check-permission:
    runs-on: ubuntu-latest
    steps:
      # this action will fail the whole workflow if permission check fails
      - name: check permission
        uses: zowe-actions/shared-actions/permission-check@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-test:
    runs-on: ubuntu-latest
    needs: check-permission
    steps: 
      - name: '[Prep 1] Checkout'
        uses: actions/checkout@v4

      - name: '[Prep 2] Setup jFrog CLI'
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_TOKEN }}

      - name: '[Prep 3] Set date'
        id: date
        run: echo "date=$(date +'%Y%m%d%S')" >> $GITHUB_OUTPUT

      - name: '[Prep 4] Set version'
        id: version
        run: |
            echo "version=$(cat manifest.yaml | grep version | cut -f 2 -d: | awk '{$1=$1};1')" >> $GITHUB_OUTPUT 

      - name: '[Prep 5] Set branchname'
        id: branch
        run: echo "branch=$(if [ -n '${{ github.head_ref }}' ]; then echo '${{ github.head_ref }}' | tr '[:lower:]' '[:upper:]'; else echo '${{ github.ref_name }}' | tr '[:lower:]' '[:upper:]'; fi | sed 's@/@-@g')" >> $GITHUB_OUTPUT


      - name: '[Prep 6] Prepare workflow'
        uses: zowe-actions/shared-actions/prepare-workflow@main

      - name: '[Prep 7] Embed build metadata'
        uses: zowe-actions/shared-actions/embed-metadata@main
        with:
          target-file: manifest.yaml
          metadata-format: YAML
          branch-name: ${{ github.head_ref || '' }}

      - name: '[Packaging] Make pax'
        uses: zowe-actions/shared-actions/make-pax@main
        with:
          pax-name: 'keyring-util'
          pax-options: '-x os390 -pp'
          pax-local-workspace: './.pax'
          pax-ssh-username: ${{ secrets.SSH_MARIST_USERNAME }}
          pax-ssh-password: ${{ secrets.SSH_MARIST_RACF_PASSWORD }}

      - name: '[Publish] Publish'
        uses: zowe-actions/shared-actions/publish@main
        if: success()
        with:
          artifacts: |
            .pax/keyring-util.pax
          publish-target-path-pattern: "{repository}/org/zowe/keyring-utilities/{version}{branchtag-uc}/"
          perform-release: ${{ github.event.inputs.PERFORM_RELEASE }}
          sigstore-sign-artifacts: true
        env:
          IS_RELEASE_BRANCH: ${{ (github.head_ref || github.ref_name) == 'master '}}
 
      - name: '[Prep Release] Bump version'
        if: ${{ github.event.inputs.PERFORM_RELEASE == 'true' }}
        uses: zowe-actions/shared-actions/bump-version@1200522c98e6db942d6f5e52267aec0fd120470a
        with:
          version: 'MINOR'
        env: 
         GITHUB_TOKEN: ${{ secrets.ZOWE_ROBOT_TOKEN }}
